name: Chat Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/chat/**"
      - .github/workflows/chat.yml

defaults:
  run:
    working-directory: examples/chat

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: hathora-cloud deploy --appId app-b32ab329-614f-42fc-9e99-49ceb3b2d3f4 --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: HATHORA_APP_ID=app-b32ab329-614f-42fc-9e99-49ceb3b2d3f4 ts-node ../../src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-chat.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
