name: Codenames Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/codenames/**"
      - .github/workflows/codenames.yml

defaults:
  run:
    working-directory: examples/codenames

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: hathora-cloud deploy --appId app-f932714b-707c-448a-9e36-706f8ae6d7bf --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: HATHORA_APP_ID=app-f932714b-707c-448a-9e36-706f8ae6d7bf ts-node ../../src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-codenames.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
