name: Poker Deploy
on:
  push:
    branches:
      - develop
    paths:
      - "examples/poker/**"
      - .github/workflows/poker.yml

defaults:
  run:
    working-directory: examples/poker

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: hathora-cloud deploy --appId app-c6802174-e24f-4eae-9feb-5d951ce31f78 --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: HATHORA_APP_ID=app-c6802174-e24f-4eae-9feb-5d951ce31f78 ts-node ../../src/cli.ts build --only client
      - run: cp client/prototype-ui/dist/index.html client/prototype-ui/dist/200.html
      - run: surge client/prototype-ui/dist hathora-poker.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  frontend-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install ts-node surge -g
      - run: HATHORA_APP_ID=app-c6802174-e24f-4eae-9feb-5d951ce31f78 ts-node ../../src/cli.ts build --only client
      - run: cp client/web/dist/index.html client/web/dist/200.html
      - run: surge client/web/dist screeching-chance.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
